/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/storage/v2/storage.proto
package com.google.storage.v2;

/**
 * <pre>
 * Request message for DeleteBucket.
 * </pre>
 *
 * Protobuf type {@code google.storage.v2.DeleteBucketRequest}
 */
public final class // @@protoc_insertion_point(message_implements:google.storage.v2.DeleteBucketRequest)
// @@protoc_insertion_point(message_implements:google.storage.v2.DeleteBucketRequest)
DeleteBucketRequest extends com.google.protobuf.GeneratedMessageV3 implements DeleteBucketRequestOrBuilder {

    private static final long serialVersionUID = 0L;

    private int bitField0_;

    public static final int NAME_FIELD_NUMBER = 1;

    private volatile java.lang.Object name_;

    public static final int IF_METAGENERATION_MATCH_FIELD_NUMBER = 2;

    private long ifMetagenerationMatch_;

    public static final int IF_METAGENERATION_NOT_MATCH_FIELD_NUMBER = 3;

    private long ifMetagenerationNotMatch_;

    private byte memoizedIsInitialized = -1;

    /**
     * <pre>
     * Request message for DeleteBucket.
     * </pre>
     *
     * Protobuf type {@code google.storage.v2.DeleteBucketRequest}
     */
    public static final class // @@protoc_insertion_point(builder_implements:google.storage.v2.DeleteBucketRequest)
    // @@protoc_insertion_point(builder_implements:google.storage.v2.DeleteBucketRequest)
    Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements com.google.storage.v2.DeleteBucketRequestOrBuilder {

        private int bitField0_;

        private java.lang.Object name_ = "";

        private long ifMetagenerationMatch_;

        private long ifMetagenerationNotMatch_;

        // @@protoc_insertion_point(builder_scope:google.storage.v2.DeleteBucketRequest)

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
            }
        }

        /**
         * <pre>
         * If set, only deletes the bucket if its metageneration does not match this
         * value.
         * </pre>
         *
         * <code>optional int64 if_metageneration_not_match = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearIfMetagenerationNotMatch() {
            bitField0_ = (bitField0_ & ~0x00000002);
            ifMetagenerationNotMatch_ = 0L;
            onChanged();
            return this;
        }

        @java.lang.Override
        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        /**
         * <pre>
         * If set, only deletes the bucket if its metageneration matches this value.
         * </pre>
         *
         * <code>optional int64 if_metageneration_match = 2;</code>
         *
         * @return The ifMetagenerationMatch.
         */
        @java.lang.Override
        public long getIfMetagenerationMatch() {
            return ifMetagenerationMatch_;
        }

        /**
         * <pre>
         * Required. Name of a bucket to delete.
         * </pre>
         *
         * <code>
         * string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
         * </code>
         *
         * @param value The bytes for name to set.
         * @return This builder for chaining.
         */
        public Builder setNameBytes(com.google.protobuf.ByteString value) {
            if (null == value) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            name_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * If set, only deletes the bucket if its metageneration does not match this
         * value.
         * </pre>
         *
         * <code>optional int64 if_metageneration_not_match = 3;</code>
         *
         * @return Whether the ifMetagenerationNotMatch field is set.
         */
        @java.lang.Override
        public boolean hasIfMetagenerationNotMatch() {
            return (0 != (bitField0_ & 0x00000002));
        }

        /**
         * <pre>
         * Required. Name of a bucket to delete.
         * </pre>
         *
         * <code>
         * string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
         * </code>
         *
         * @return This builder for chaining.
         */
        public Builder clearName() {
            name_ = getDefaultInstance().getName();
            onChanged();
            return this;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return StorageProto.internal_static_google_storage_v2_DeleteBucketRequest_fieldAccessorTable.ensureFieldAccessorsInitialized(DeleteBucketRequest.class, Builder.class);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            DeleteBucketRequest parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (DeleteBucketRequest) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (null != parsedMessage) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <pre>
         * If set, only deletes the bucket if its metageneration matches this value.
         * </pre>
         *
         * <code>optional int64 if_metageneration_match = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearIfMetagenerationMatch() {
            bitField0_ = (bitField0_ & ~0x00000001);
            ifMetagenerationMatch_ = 0L;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * If set, only deletes the bucket if its metageneration matches this value.
         * </pre>
         *
         * <code>optional int64 if_metageneration_match = 2;</code>
         *
         * @param value The ifMetagenerationMatch to set.
         * @return This builder for chaining.
         */
        public Builder setIfMetagenerationMatch(long value) {
            bitField0_ |= 0x00000001;
            ifMetagenerationMatch_ = value;
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        /**
         * <pre>
         * Required. Name of a bucket to delete.
         * </pre>
         *
         * <code>
         * string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
         * </code>
         *
         * @param value The name to set.
         * @return This builder for chaining.
         */
        public Builder setName(java.lang.String value) {
            if (null == value) {
                throw new NullPointerException();
            }
            name_ = value;
            onChanged();
            return this;
        }

        public Builder mergeFrom(DeleteBucketRequest other) {
            if (DeleteBucketRequest.getDefaultInstance() == other)
                return this;
            if (!other.getName().isEmpty()) {
                name_ = other.name_;
                onChanged();
            }
            if (other.hasIfMetagenerationMatch()) {
                setIfMetagenerationMatch(other.getIfMetagenerationMatch());
            }
            if (other.hasIfMetagenerationNotMatch()) {
                setIfMetagenerationNotMatch(other.getIfMetagenerationNotMatch());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public DeleteBucketRequest getDefaultInstanceForType() {
            return DeleteBucketRequest.getDefaultInstance();
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public DeleteBucketRequest buildPartial() {
            DeleteBucketRequest result = new DeleteBucketRequest(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            result.name_ = name_;
            if ((0 != (from_bitField0_ & 0x00000001))) {
                result.ifMetagenerationMatch_ = ifMetagenerationMatch_;
                to_bitField0_ |= 0x00000001;
            }
            if ((0 != (from_bitField0_ & 0x00000002))) {
                result.ifMetagenerationNotMatch_ = ifMetagenerationNotMatch_;
                to_bitField0_ |= 0x00000002;
            }
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public DeleteBucketRequest build() {
            DeleteBucketRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        /**
         * <pre>
         * Required. Name of a bucket to delete.
         * </pre>
         *
         * <code>
         * string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
         * </code>
         *
         * @return The bytes for name.
         */
        public com.google.protobuf.ByteString getNameBytes() {
            java.lang.Object ref = name_;
            if (!(ref instanceof String)) {
                return (com.google.protobuf.ByteString) ref;
            } else {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                name_ = b;
                return b;
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return StorageProto.internal_static_google_storage_v2_DeleteBucketRequest_descriptor;
        }

        @java.lang.Override
        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        /**
         * <pre>
         * If set, only deletes the bucket if its metageneration does not match this
         * value.
         * </pre>
         *
         * <code>optional int64 if_metageneration_not_match = 3;</code>
         *
         * @param value The ifMetagenerationNotMatch to set.
         * @return This builder for chaining.
         */
        public Builder setIfMetagenerationNotMatch(long value) {
            bitField0_ |= 0x00000002;
            ifMetagenerationNotMatch_ = value;
            onChanged();
            return this;
        }

        @java.lang.Override
        public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        /**
         * <pre>
         * Required. Name of a bucket to delete.
         * </pre>
         *
         * <code>
         * string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
         * </code>
         *
         * @return The name.
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if ((ref instanceof java.lang.String)) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * If set, only deletes the bucket if its metageneration does not match this
         * value.
         * </pre>
         *
         * <code>optional int64 if_metageneration_not_match = 3;</code>
         *
         * @return The ifMetagenerationNotMatch.
         */
        @java.lang.Override
        public long getIfMetagenerationNotMatch() {
            return ifMetagenerationNotMatch_;
        }

        /**
         * <pre>
         * If set, only deletes the bucket if its metageneration matches this value.
         * </pre>
         *
         * <code>optional int64 if_metageneration_match = 2;</code>
         *
         * @return Whether the ifMetagenerationMatch field is set.
         */
        @java.lang.Override
        public boolean hasIfMetagenerationMatch() {
            return (0 != (bitField0_ & 0x00000001));
        }

        private Builder(BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        @java.lang.Override
        public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            name_ = "";
            ifMetagenerationMatch_ = 0L;
            bitField0_ = (bitField0_ & ~0x00000001);
            ifMetagenerationNotMatch_ = 0L;
            bitField0_ = (bitField0_ & ~0x00000002);
            return this;
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (!(other instanceof DeleteBucketRequest)) {
                super.mergeFrom(other);
                return this;
            } else {
                return mergeFrom((DeleteBucketRequest) other);
            }
        }

        // Construct using com.google.storage.v2.DeleteBucketRequest.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return StorageProto.internal_static_google_storage_v2_DeleteBucketRequest_descriptor;
        }

        @java.lang.Override
        public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.setField(field, value);
        }

    }

    // @@protoc_insertion_point(class_scope:google.storage.v2.DeleteBucketRequest)
    private static final com.google.storage.v2.DeleteBucketRequest DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new com.google.storage.v2.DeleteBucketRequest();
    }

    private static final com.google.protobuf.Parser<DeleteBucketRequest> PARSER = new com.google.protobuf.AbstractParser<DeleteBucketRequest>() {

        @java.lang.Override
        public DeleteBucketRequest parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return new DeleteBucketRequest(input, extensionRegistry);
        }
    };

    public static DeleteBucketRequest parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (1 == isInitialized)
            return true;
        if (0 == isInitialized)
            return false;
        memoizedIsInitialized = 1;
        return true;
    }

    // Use DeleteBucketRequest.newBuilder() to construct.
    private DeleteBucketRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    public static DeleteBucketRequest parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.google.protobuf.Parser<DeleteBucketRequest> parser() {
        return PARSER;
    }

    public static DeleteBucketRequest parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static DeleteBucketRequest parseFrom(java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return StorageProto.internal_static_google_storage_v2_DeleteBucketRequest_descriptor;
    }

    @java.lang.Override
    protected Builder newBuilderForType(BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    public static DeleteBucketRequest parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static DeleteBucketRequest parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeleteBucketRequest> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
        return this.unknownFields;
    }

    @java.lang.Override
    public Builder toBuilder() {
        return DEFAULT_INSTANCE == this ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    public DeleteBucketRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static DeleteBucketRequest parseFrom(java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    /**
     * <pre>
     * If set, only deletes the bucket if its metageneration does not match this
     * value.
     * </pre>
     *
     * <code>optional int64 if_metageneration_not_match = 3;</code>
     *
     * @return The ifMetagenerationNotMatch.
     */
    @java.lang.Override
    public long getIfMetagenerationNotMatch() {
        return ifMetagenerationNotMatch_;
    }

    public static DeleteBucketRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    /**
     * <pre>
     * If set, only deletes the bucket if its metageneration matches this value.
     * </pre>
     *
     * <code>optional int64 if_metageneration_match = 2;</code>
     *
     * @return Whether the ifMetagenerationMatch field is set.
     */
    @java.lang.Override
    public boolean hasIfMetagenerationMatch() {
        return (0 != (bitField0_ & 0x00000001));
    }

    public static DeleteBucketRequest parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    private DeleteBucketRequest() {
        name_ = "";
    }

    private DeleteBucketRequest(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (null == extensionRegistry) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch(tag) {
                    case 0:
                        done = true;
                        break;
                    case 10:
                        {
                            java.lang.String s = input.readStringRequireUtf8();
                            name_ = s;
                            break;
                        }
                    case 16:
                        {
                            bitField0_ |= 0x00000001;
                            ifMetagenerationMatch_ = input.readInt64();
                            break;
                        }
                    case 24:
                        {
                            bitField0_ |= 0x00000002;
                            ifMetagenerationNotMatch_ = input.readInt64();
                            break;
                        }
                    default:
                        {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    @java.lang.Override
    public int hashCode() {
        if (0 != memoizedHashCode) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        if (hasIfMetagenerationMatch()) {
            hash = (37 * hash) + IF_METAGENERATION_MATCH_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getIfMetagenerationMatch());
        }
        if (hasIfMetagenerationNotMatch()) {
            hash = (37 * hash) + IF_METAGENERATION_NOT_MATCH_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getIfMetagenerationNotMatch());
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    /**
     * <pre>
     * Required. Name of a bucket to delete.
     * </pre>
     *
     * <code>
     * string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
     * </code>
     *
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNameBytes() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
            return (com.google.protobuf.ByteString) ref;
        } else {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            name_ = b;
            return b;
        }
    }

    public static Builder newBuilder(DeleteBucketRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static DeleteBucketRequest parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static DeleteBucketRequest parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return StorageProto.internal_static_google_storage_v2_DeleteBucketRequest_fieldAccessorTable.ensureFieldAccessorsInitialized(DeleteBucketRequest.class, Builder.class);
    }

    @java.lang.Override
    @SuppressWarnings({ "unused" })
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
        return new DeleteBucketRequest();
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (-1 != size)
            return size;
        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
        }
        if ((0 != (bitField0_ & 0x00000001))) {
            size += com.google.protobuf.CodedOutputStream.computeInt64Size(2, ifMetagenerationMatch_);
        }
        if ((0 != (bitField0_ & 0x00000002))) {
            size += com.google.protobuf.CodedOutputStream.computeInt64Size(3, ifMetagenerationNotMatch_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    /**
     * <pre>
     * Required. Name of a bucket to delete.
     * </pre>
     *
     * <code>
     * string name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
     * </code>
     *
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
        } else {
            return (java.lang.String) ref;
        }
    }

    /**
     * <pre>
     * If set, only deletes the bucket if its metageneration does not match this
     * value.
     * </pre>
     *
     * <code>optional int64 if_metageneration_not_match = 3;</code>
     *
     * @return Whether the ifMetagenerationNotMatch field is set.
     */
    @java.lang.Override
    public boolean hasIfMetagenerationNotMatch() {
        return (0 != (bitField0_ & 0x00000002));
    }

    public static DeleteBucketRequest parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static DeleteBucketRequest parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
        }
        if ((0 != (bitField0_ & 0x00000001))) {
            output.writeInt64(2, ifMetagenerationMatch_);
        }
        if ((0 != (bitField0_ & 0x00000002))) {
            output.writeInt64(3, ifMetagenerationNotMatch_);
        }
        unknownFields.writeTo(output);
    }

    /**
     * <pre>
     * If set, only deletes the bucket if its metageneration matches this value.
     * </pre>
     *
     * <code>optional int64 if_metageneration_match = 2;</code>
     *
     * @return The ifMetagenerationMatch.
     */
    @java.lang.Override
    public long getIfMetagenerationMatch() {
        return ifMetagenerationMatch_;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof DeleteBucketRequest)) {
            return super.equals(obj);
        }
        DeleteBucketRequest other = (DeleteBucketRequest) obj;
        if (!getName().equals(other.getName()))
            return false;
        if (other.hasIfMetagenerationMatch() != hasIfMetagenerationMatch())
            return false;
        if (hasIfMetagenerationMatch()) {
            if (other.getIfMetagenerationMatch() != getIfMetagenerationMatch())
                return false;
        }
        if (other.hasIfMetagenerationNotMatch() != hasIfMetagenerationNotMatch())
            return false;
        if (hasIfMetagenerationNotMatch()) {
            if (other.getIfMetagenerationNotMatch() != getIfMetagenerationNotMatch())
                return false;
        }
        if (!unknownFields.equals(other.unknownFields))
            return false;
        return true;
    }

}
