/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/storage/v2/storage.proto
package com.google.storage.v2;

/**
 * <pre>
 * The result of a call to Buckets.ListBuckets
 * </pre>
 *
 * Protobuf type {@code google.storage.v2.ListBucketsResponse}
 */
public final class // @@protoc_insertion_point(message_implements:google.storage.v2.ListBucketsResponse)
// @@protoc_insertion_point(message_implements:google.storage.v2.ListBucketsResponse)
ListBucketsResponse extends com.google.protobuf.GeneratedMessageV3 implements ListBucketsResponseOrBuilder {

    private static final long serialVersionUID = 0L;

    public static final int BUCKETS_FIELD_NUMBER = 1;

    private java.util.List<com.google.storage.v2.Bucket> buckets_;

    public static final int NEXT_PAGE_TOKEN_FIELD_NUMBER = 2;

    private volatile java.lang.Object nextPageToken_;

    private byte memoizedIsInitialized = -1;

    /**
     * <pre>
     * The result of a call to Buckets.ListBuckets
     * </pre>
     *
     * Protobuf type {@code google.storage.v2.ListBucketsResponse}
     */
    public static final class // @@protoc_insertion_point(builder_implements:google.storage.v2.ListBucketsResponse)
    // @@protoc_insertion_point(builder_implements:google.storage.v2.ListBucketsResponse)
    Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements com.google.storage.v2.ListBucketsResponseOrBuilder {

        private int bitField0_;

        private java.util.List<com.google.storage.v2.Bucket> buckets_ = java.util.Collections.emptyList();

        private com.google.protobuf.RepeatedFieldBuilderV3<com.google.storage.v2.Bucket, com.google.storage.v2.Bucket.Builder, com.google.storage.v2.BucketOrBuilder> bucketsBuilder_;

        private java.lang.Object nextPageToken_ = "";

        // @@protoc_insertion_point(builder_scope:google.storage.v2.ListBucketsResponse)

        /**
         * <pre>
         * The continuation token, used to page through large result sets. Provide
         * this value in a subsequent request to return the next page of results.
         * </pre>
         *
         * <code>string next_page_token = 2;</code>
         *
         * @return The nextPageToken.
         */
        public java.lang.String getNextPageToken() {
            java.lang.Object ref = nextPageToken_;
            if ((ref instanceof java.lang.String)) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                nextPageToken_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * The continuation token, used to page through large result sets. Provide
         * this value in a subsequent request to return the next page of results.
         * </pre>
         *
         * <code>string next_page_token = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearNextPageToken() {
            nextPageToken_ = getDefaultInstance().getNextPageToken();
            onChanged();
            return this;
        }

        @java.lang.Override
        public ListBucketsResponse build() {
            ListBucketsResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        /**
         * <pre>
         * The list of items.
         * </pre>
         *
         * <code>repeated .google.storage.v2.Bucket buckets = 1;</code>
         */
        public Builder clearBuckets() {
            if (null != bucketsBuilder_) {
                bucketsBuilder_.clear();
            } else {
                buckets_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
            }
            return this;
        }

        /**
         * <pre>
         * The continuation token, used to page through large result sets. Provide
         * this value in a subsequent request to return the next page of results.
         * </pre>
         *
         * <code>string next_page_token = 2;</code>
         *
         * @return The bytes for nextPageToken.
         */
        public com.google.protobuf.ByteString getNextPageTokenBytes() {
            java.lang.Object ref = nextPageToken_;
            if (!(ref instanceof String)) {
                return (com.google.protobuf.ByteString) ref;
            } else {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                nextPageToken_ = b;
                return b;
            }
        }

        /**
         * <pre>
         * The continuation token, used to page through large result sets. Provide
         * this value in a subsequent request to return the next page of results.
         * </pre>
         *
         * <code>string next_page_token = 2;</code>
         *
         * @param value The bytes for nextPageToken to set.
         * @return This builder for chaining.
         */
        public Builder setNextPageTokenBytes(com.google.protobuf.ByteString value) {
            if (null == value) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            nextPageToken_ = value;
            onChanged();
            return this;
        }

        @java.lang.Override
        public ListBucketsResponse buildPartial() {
            ListBucketsResponse result = new ListBucketsResponse(this);
            int from_bitField0_ = bitField0_;
            if (null != bucketsBuilder_) {
                result.buckets_ = bucketsBuilder_.build();
            } else {
                if ((0 != (bitField0_ & 0x00000001))) {
                    buckets_ = java.util.Collections.unmodifiableList(buckets_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.buckets_ = buckets_;
            }
            result.nextPageToken_ = nextPageToken_;
            onBuilt();
            return result;
        }

        /**
         * <pre>
         * The list of items.
         * </pre>
         *
         * <code>repeated .google.storage.v2.Bucket buckets = 1;</code>
         */
        public Builder addBuckets(Bucket.Builder builderForValue) {
            if (null != bucketsBuilder_) {
                bucketsBuilder_.addMessage(builderForValue.build());
            } else {
                ensureBucketsIsMutable();
                buckets_.add(builderForValue.build());
                onChanged();
            }
            return this;
        }

        /**
         * <pre>
         * The list of items.
         * </pre>
         *
         * <code>repeated .google.storage.v2.Bucket buckets = 1;</code>
         */
        public Builder addAllBuckets(java.lang.Iterable<? extends Bucket> values) {
            if (null != bucketsBuilder_) {
                bucketsBuilder_.addAllMessages(values);
            } else {
                ensureBucketsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(values, buckets_);
                onChanged();
            }
            return this;
        }

        /**
         * <pre>
         * The list of items.
         * </pre>
         *
         * <code>repeated .google.storage.v2.Bucket buckets = 1;</code>
         */
        public BucketOrBuilder getBucketsOrBuilder(int index) {
            if (null != bucketsBuilder_) {
                return bucketsBuilder_.getMessageOrBuilder(index);
            } else {
                return buckets_.get(index);
            }
        }

        /**
         * <pre>
         * The list of items.
         * </pre>
         *
         * <code>repeated .google.storage.v2.Bucket buckets = 1;</code>
         */
        public Bucket.Builder addBucketsBuilder(int index) {
            return getBucketsFieldBuilder().addBuilder(index, Bucket.getDefaultInstance());
        }

        /**
         * <pre>
         * The list of items.
         * </pre>
         *
         * <code>repeated .google.storage.v2.Bucket buckets = 1;</code>
         */
        public java.util.List<? extends BucketOrBuilder> getBucketsOrBuilderList() {
            if (null == bucketsBuilder_) {
                return java.util.Collections.unmodifiableList(buckets_);
            } else {
                return bucketsBuilder_.getMessageOrBuilderList();
            }
        }

        /**
         * <pre>
         * The list of items.
         * </pre>
         *
         * <code>repeated .google.storage.v2.Bucket buckets = 1;</code>
         */
        public Bucket.Builder getBucketsBuilder(int index) {
            return getBucketsFieldBuilder().getBuilder(index);
        }

        @java.lang.Override
        public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        /**
         * <pre>
         * The list of items.
         * </pre>
         *
         * <code>repeated .google.storage.v2.Bucket buckets = 1;</code>
         */
        public Builder addBuckets(Bucket value) {
            if (null != bucketsBuilder_) {
                bucketsBuilder_.addMessage(value);
            } else {
                if (null == value) {
                    throw new NullPointerException();
                }
                ensureBucketsIsMutable();
                buckets_.add(value);
                onChanged();
            }
            return this;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<Bucket, Bucket.Builder, BucketOrBuilder> getBucketsFieldBuilder() {
            if (null == bucketsBuilder_) {
                bucketsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<Bucket, Bucket.Builder, BucketOrBuilder>(buckets_, (0 != (bitField0_ & 0x00000001)), getParentForChildren(), isClean());
                buckets_ = null;
            }
            return bucketsBuilder_;
        }

        /**
         * <pre>
         * The list of items.
         * </pre>
         *
         * <code>repeated .google.storage.v2.Bucket buckets = 1;</code>
         */
        public Builder addBuckets(int index, Bucket.Builder builderForValue) {
            if (null != bucketsBuilder_) {
                bucketsBuilder_.addMessage(index, builderForValue.build());
            } else {
                ensureBucketsIsMutable();
                buckets_.add(index, builderForValue.build());
                onChanged();
            }
            return this;
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            if (null != bucketsBuilder_) {
                bucketsBuilder_.clear();
            } else {
                buckets_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
            }
            nextPageToken_ = "";
            return this;
        }

        /**
         * <pre>
         * The list of items.
         * </pre>
         *
         * <code>repeated .google.storage.v2.Bucket buckets = 1;</code>
         */
        public Bucket getBuckets(int index) {
            if (null != bucketsBuilder_) {
                return bucketsBuilder_.getMessage(index);
            } else {
                return buckets_.get(index);
            }
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        /**
         * <pre>
         * The list of items.
         * </pre>
         *
         * <code>repeated .google.storage.v2.Bucket buckets = 1;</code>
         */
        public Builder removeBuckets(int index) {
            if (null != bucketsBuilder_) {
                bucketsBuilder_.remove(index);
            } else {
                ensureBucketsIsMutable();
                buckets_.remove(index);
                onChanged();
            }
            return this;
        }

        /**
         * <pre>
         * The list of items.
         * </pre>
         *
         * <code>repeated .google.storage.v2.Bucket buckets = 1;</code>
         */
        public Builder setBuckets(int index, Bucket value) {
            if (null != bucketsBuilder_) {
                bucketsBuilder_.setMessage(index, value);
            } else {
                if (null == value) {
                    throw new NullPointerException();
                }
                ensureBucketsIsMutable();
                buckets_.set(index, value);
                onChanged();
            }
            return this;
        }

        /**
         * <pre>
         * The list of items.
         * </pre>
         *
         * <code>repeated .google.storage.v2.Bucket buckets = 1;</code>
         */
        public java.util.List<Bucket> getBucketsList() {
            if (null != bucketsBuilder_) {
                return bucketsBuilder_.getMessageList();
            } else {
                return java.util.Collections.unmodifiableList(buckets_);
            }
        }

        private Builder(BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        /**
         * <pre>
         * The list of items.
         * </pre>
         *
         * <code>repeated .google.storage.v2.Bucket buckets = 1;</code>
         */
        public int getBucketsCount() {
            if (null != bucketsBuilder_) {
                return bucketsBuilder_.getCount();
            } else {
                return buckets_.size();
            }
        }

        /**
         * <pre>
         * The list of items.
         * </pre>
         *
         * <code>repeated .google.storage.v2.Bucket buckets = 1;</code>
         */
        public Builder setBuckets(int index, Bucket.Builder builderForValue) {
            if (null != bucketsBuilder_) {
                bucketsBuilder_.setMessage(index, builderForValue.build());
            } else {
                ensureBucketsIsMutable();
                buckets_.set(index, builderForValue.build());
                onChanged();
            }
            return this;
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return StorageProto.internal_static_google_storage_v2_ListBucketsResponse_descriptor;
        }

        private void ensureBucketsIsMutable() {
            if (!(0 != (bitField0_ & 0x00000001))) {
                buckets_ = new java.util.ArrayList<Bucket>(buckets_);
                bitField0_ |= 0x00000001;
            }
        }

        @java.lang.Override
        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public ListBucketsResponse getDefaultInstanceForType() {
            return ListBucketsResponse.getDefaultInstance();
        }

        /**
         * <pre>
         * The list of items.
         * </pre>
         *
         * <code>repeated .google.storage.v2.Bucket buckets = 1;</code>
         */
        public Builder addBuckets(int index, Bucket value) {
            if (null != bucketsBuilder_) {
                bucketsBuilder_.addMessage(index, value);
            } else {
                if (null == value) {
                    throw new NullPointerException();
                }
                ensureBucketsIsMutable();
                buckets_.add(index, value);
                onChanged();
            }
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return StorageProto.internal_static_google_storage_v2_ListBucketsResponse_descriptor;
        }

        /**
         * <pre>
         * The continuation token, used to page through large result sets. Provide
         * this value in a subsequent request to return the next page of results.
         * </pre>
         *
         * <code>string next_page_token = 2;</code>
         *
         * @param value The nextPageToken to set.
         * @return This builder for chaining.
         */
        public Builder setNextPageToken(java.lang.String value) {
            if (null == value) {
                throw new NullPointerException();
            }
            nextPageToken_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * The list of items.
         * </pre>
         *
         * <code>repeated .google.storage.v2.Bucket buckets = 1;</code>
         */
        public java.util.List<Bucket.Builder> getBucketsBuilderList() {
            return getBucketsFieldBuilder().getBuilderList();
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }

        @java.lang.Override
        public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            ListBucketsResponse parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (ListBucketsResponse) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (null != parsedMessage) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <pre>
         * The list of items.
         * </pre>
         *
         * <code>repeated .google.storage.v2.Bucket buckets = 1;</code>
         */
        public Bucket.Builder addBucketsBuilder() {
            return getBucketsFieldBuilder().addBuilder(Bucket.getDefaultInstance());
        }

        @java.lang.Override
        public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                getBucketsFieldBuilder();
            }
        }

        @java.lang.Override
        public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        // Construct using com.google.storage.v2.ListBucketsResponse.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        @java.lang.Override
        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        public Builder mergeFrom(ListBucketsResponse other) {
            if (ListBucketsResponse.getDefaultInstance() == other)
                return this;
            if (null != bucketsBuilder_) {
                if (!other.buckets_.isEmpty()) {
                    if (!bucketsBuilder_.isEmpty()) {
                        bucketsBuilder_.addAllMessages(other.buckets_);
                    } else {
                        bucketsBuilder_.dispose();
                        bucketsBuilder_ = null;
                        buckets_ = other.buckets_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                        bucketsBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ? getBucketsFieldBuilder() : null;
                    }
                }
            } else {
                if (!other.buckets_.isEmpty()) {
                    if (!buckets_.isEmpty()) {
                        ensureBucketsIsMutable();
                        buckets_.addAll(other.buckets_);
                    } else {
                        buckets_ = other.buckets_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    onChanged();
                }
            }
            if (!other.getNextPageToken().isEmpty()) {
                nextPageToken_ = other.nextPageToken_;
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (!(other instanceof ListBucketsResponse)) {
                super.mergeFrom(other);
                return this;
            } else {
                return mergeFrom((ListBucketsResponse) other);
            }
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return StorageProto.internal_static_google_storage_v2_ListBucketsResponse_fieldAccessorTable.ensureFieldAccessorsInitialized(ListBucketsResponse.class, Builder.class);
        }

    }

    // @@protoc_insertion_point(class_scope:google.storage.v2.ListBucketsResponse)
    private static final com.google.storage.v2.ListBucketsResponse DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new com.google.storage.v2.ListBucketsResponse();
    }

    private static final com.google.protobuf.Parser<ListBucketsResponse> PARSER = new com.google.protobuf.AbstractParser<ListBucketsResponse>() {

        @java.lang.Override
        public ListBucketsResponse parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return new ListBucketsResponse(input, extensionRegistry);
        }
    };

    /**
     * <pre>
     * The list of items.
     * </pre>
     *
     * <code>repeated .google.storage.v2.Bucket buckets = 1;</code>
     */
    @java.lang.Override
    public java.util.List<Bucket> getBucketsList() {
        return buckets_;
    }

    /**
     * <pre>
     * The continuation token, used to page through large result sets. Provide
     * this value in a subsequent request to return the next page of results.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     *
     * @return The nextPageToken.
     */
    @java.lang.Override
    public java.lang.String getNextPageToken() {
        java.lang.Object ref = nextPageToken_;
        if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            nextPageToken_ = s;
            return s;
        } else {
            return (java.lang.String) ref;
        }
    }

    @java.lang.Override
    public ListBucketsResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    public static ListBucketsResponse parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static ListBucketsResponse parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static ListBucketsResponse parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    /**
     * <pre>
     * The list of items.
     * </pre>
     *
     * <code>repeated .google.storage.v2.Bucket buckets = 1;</code>
     */
    @java.lang.Override
    public Bucket getBuckets(int index) {
        return buckets_.get(index);
    }

    public static ListBucketsResponse parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static ListBucketsResponse parseFrom(java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static ListBucketsResponse parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static ListBucketsResponse parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder(ListBucketsResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return StorageProto.internal_static_google_storage_v2_ListBucketsResponse_descriptor;
    }

    public static ListBucketsResponse parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (-1 != size)
            return size;
        size = 0;
        int i = 0;
        while (buckets_.size() > i) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, buckets_.get(i));
            i += 1;
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nextPageToken_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nextPageToken_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListBucketsResponse> getParserForType() {
        return PARSER;
    }

    public static ListBucketsResponse parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    @java.lang.Override
    @SuppressWarnings({ "unused" })
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
        return new ListBucketsResponse();
    }

    public static ListBucketsResponse parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    /**
     * <pre>
     * The continuation token, used to page through large result sets. Provide
     * this value in a subsequent request to return the next page of results.
     * </pre>
     *
     * <code>string next_page_token = 2;</code>
     *
     * @return The bytes for nextPageToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNextPageTokenBytes() {
        java.lang.Object ref = nextPageToken_;
        if (!(ref instanceof java.lang.String)) {
            return (com.google.protobuf.ByteString) ref;
        } else {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            nextPageToken_ = b;
            return b;
        }
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return StorageProto.internal_static_google_storage_v2_ListBucketsResponse_fieldAccessorTable.ensureFieldAccessorsInitialized(ListBucketsResponse.class, Builder.class);
    }

    // Use ListBucketsResponse.newBuilder() to construct.
    private ListBucketsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    public static com.google.protobuf.Parser<ListBucketsResponse> parser() {
        return PARSER;
    }

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (1 == isInitialized)
            return true;
        if (0 == isInitialized)
            return false;
        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    protected Builder newBuilderForType(BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * <pre>
     * The list of items.
     * </pre>
     *
     * <code>repeated .google.storage.v2.Bucket buckets = 1;</code>
     */
    @java.lang.Override
    public int getBucketsCount() {
        return buckets_.size();
    }

    @java.lang.Override
    public int hashCode() {
        if (0 != memoizedHashCode) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (0 < getBucketsCount()) {
            hash = (37 * hash) + BUCKETS_FIELD_NUMBER;
            hash = (53 * hash) + getBucketsList().hashCode();
        }
        hash = (37 * hash) + NEXT_PAGE_TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getNextPageToken().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @java.lang.Override
    public Builder toBuilder() {
        return DEFAULT_INSTANCE == this ? new Builder() : new Builder().mergeFrom(this);
    }

    public static ListBucketsResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private ListBucketsResponse(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (null == extensionRegistry) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch(tag) {
                    case 0:
                        done = true;
                        break;
                    case 10:
                        {
                            if (!(0 != (mutable_bitField0_ & 0x00000001))) {
                                buckets_ = new java.util.ArrayList<Bucket>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            buckets_.add(input.readMessage(Bucket.parser(), extensionRegistry));
                            break;
                        }
                    case 18:
                        {
                            java.lang.String s = input.readStringRequireUtf8();
                            nextPageToken_ = s;
                            break;
                        }
                    default:
                        {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
        } finally {
            if ((0 != (mutable_bitField0_ & 0x00000001))) {
                buckets_ = java.util.Collections.unmodifiableList(buckets_);
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static ListBucketsResponse parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ListBucketsResponse parseFrom(java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    /**
     * <pre>
     * The list of items.
     * </pre>
     *
     * <code>repeated .google.storage.v2.Bucket buckets = 1;</code>
     */
    @java.lang.Override
    public BucketOrBuilder getBucketsOrBuilder(int index) {
        return buckets_.get(index);
    }

    private ListBucketsResponse() {
        buckets_ = java.util.Collections.emptyList();
        nextPageToken_ = "";
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof ListBucketsResponse)) {
            return super.equals(obj);
        }
        ListBucketsResponse other = (ListBucketsResponse) obj;
        if (!getBucketsList().equals(other.getBucketsList()))
            return false;
        if (!getNextPageToken().equals(other.getNextPageToken()))
            return false;
        if (!unknownFields.equals(other.unknownFields))
            return false;
        return true;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
        return this.unknownFields;
    }

    /**
     * <pre>
     * The list of items.
     * </pre>
     *
     * <code>repeated .google.storage.v2.Bucket buckets = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends BucketOrBuilder> getBucketsOrBuilderList() {
        return buckets_;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        int i = 0;
        while (buckets_.size() > i) {
            output.writeMessage(1, buckets_.get(i));
            i += 1;
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nextPageToken_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nextPageToken_);
        }
        unknownFields.writeTo(output);
    }

}
