/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/storage/v2/storage.proto
package com.google.storage.v2;

/**
 * <pre>
 * Describes an attempt to insert an object, possibly over multiple requests.
 * </pre>
 *
 * Protobuf type {@code google.storage.v2.WriteObjectSpec}
 */
public final class // @@protoc_insertion_point(message_implements:google.storage.v2.WriteObjectSpec)
// @@protoc_insertion_point(message_implements:google.storage.v2.WriteObjectSpec)
WriteObjectSpec extends com.google.protobuf.GeneratedMessageV3 implements WriteObjectSpecOrBuilder {

    private static final long serialVersionUID = 0L;

    // Use WriteObjectSpec.newBuilder() to construct.
    private WriteObjectSpec(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private WriteObjectSpec() {
        predefinedAcl_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({ "unused" })
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
        return new WriteObjectSpec();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
        return this.unknownFields;
    }

    private WriteObjectSpec(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (null == extensionRegistry) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch(tag) {
                    case 0:
                        done = true;
                        break;
                    case 10:
                        {
                            com.google.storage.v2.Object.Builder subBuilder = null;
                            if (null != resource_) {
                                subBuilder = resource_.toBuilder();
                            }
                            resource_ = input.readMessage(com.google.storage.v2.Object.parser(), extensionRegistry);
                            if (null != subBuilder) {
                                subBuilder.mergeFrom(resource_);
                                resource_ = subBuilder.buildPartial();
                            }
                            break;
                        }
                    case 24:
                        {
                            bitField0_ |= 0x00000001;
                            ifGenerationMatch_ = input.readInt64();
                            break;
                        }
                    case 32:
                        {
                            bitField0_ |= 0x00000002;
                            ifGenerationNotMatch_ = input.readInt64();
                            break;
                        }
                    case 40:
                        {
                            bitField0_ |= 0x00000004;
                            ifMetagenerationMatch_ = input.readInt64();
                            break;
                        }
                    case 48:
                        {
                            bitField0_ |= 0x00000008;
                            ifMetagenerationNotMatch_ = input.readInt64();
                            break;
                        }
                    case 58:
                        {
                            java.lang.String s = input.readStringRequireUtf8();
                            predefinedAcl_ = s;
                            break;
                        }
                    default:
                        {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.google.storage.v2.StorageProto.internal_static_google_storage_v2_WriteObjectSpec_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.google.storage.v2.StorageProto.internal_static_google_storage_v2_WriteObjectSpec_fieldAccessorTable.ensureFieldAccessorsInitialized(com.google.storage.v2.WriteObjectSpec.class, com.google.storage.v2.WriteObjectSpec.Builder.class);
    }

    private int bitField0_;

    public static final int RESOURCE_FIELD_NUMBER = 1;

    private com.google.storage.v2.Object resource_;

    /**
     * <pre>
     * Destination object, including its name and its metadata.
     * </pre>
     *
     * <code>.google.storage.v2.Object resource = 1;</code>
     *
     * @return Whether the resource field is set.
     */
    @java.lang.Override
    public boolean hasResource() {
        return null != resource_;
    }

    /**
     * <pre>
     * Destination object, including its name and its metadata.
     * </pre>
     *
     * <code>.google.storage.v2.Object resource = 1;</code>
     *
     * @return The resource.
     */
    @java.lang.Override
    public com.google.storage.v2.Object getResource() {
        return null == resource_ ? com.google.storage.v2.Object.getDefaultInstance() : resource_;
    }

    /**
     * <pre>
     * Destination object, including its name and its metadata.
     * </pre>
     *
     * <code>.google.storage.v2.Object resource = 1;</code>
     */
    @java.lang.Override
    public com.google.storage.v2.ObjectOrBuilder getResourceOrBuilder() {
        return getResource();
    }

    public static final int PREDEFINED_ACL_FIELD_NUMBER = 7;

    private volatile java.lang.Object predefinedAcl_;

    /**
     * <pre>
     * Apply a predefined set of access controls to this object.
     * Valid values are "authenticatedRead", "bucketOwnerFullControl",
     * "bucketOwnerRead", "private", "projectPrivate", or "publicRead".
     * </pre>
     *
     * <code>string predefined_acl = 7;</code>
     *
     * @return The predefinedAcl.
     */
    @java.lang.Override
    public java.lang.String getPredefinedAcl() {
        java.lang.Object ref = predefinedAcl_;
        if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            predefinedAcl_ = s;
            return s;
        } else {
            return (java.lang.String) ref;
        }
    }

    /**
     * <pre>
     * Apply a predefined set of access controls to this object.
     * Valid values are "authenticatedRead", "bucketOwnerFullControl",
     * "bucketOwnerRead", "private", "projectPrivate", or "publicRead".
     * </pre>
     *
     * <code>string predefined_acl = 7;</code>
     *
     * @return The bytes for predefinedAcl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPredefinedAclBytes() {
        java.lang.Object ref = predefinedAcl_;
        if (!(ref instanceof java.lang.String)) {
            return (com.google.protobuf.ByteString) ref;
        } else {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            predefinedAcl_ = b;
            return b;
        }
    }

    public static final int IF_GENERATION_MATCH_FIELD_NUMBER = 3;

    private long ifGenerationMatch_;

    /**
     * <pre>
     * Makes the operation conditional on whether the object's current
     * generation matches the given value. Setting to 0 makes the operation
     * succeed only if there are no live versions of the object.
     * </pre>
     *
     * <code>optional int64 if_generation_match = 3;</code>
     *
     * @return Whether the ifGenerationMatch field is set.
     */
    @java.lang.Override
    public boolean hasIfGenerationMatch() {
        return (0 != (bitField0_ & 0x00000001));
    }

    /**
     * <pre>
     * Makes the operation conditional on whether the object's current
     * generation matches the given value. Setting to 0 makes the operation
     * succeed only if there are no live versions of the object.
     * </pre>
     *
     * <code>optional int64 if_generation_match = 3;</code>
     *
     * @return The ifGenerationMatch.
     */
    @java.lang.Override
    public long getIfGenerationMatch() {
        return ifGenerationMatch_;
    }

    public static final int IF_GENERATION_NOT_MATCH_FIELD_NUMBER = 4;

    private long ifGenerationNotMatch_;

    /**
     * <pre>
     * Makes the operation conditional on whether the object's current
     * generation does not match the given value. If no live object exists, the
     * precondition fails. Setting to 0 makes the operation succeed only if
     * there is a live version of the object.
     * </pre>
     *
     * <code>optional int64 if_generation_not_match = 4;</code>
     *
     * @return Whether the ifGenerationNotMatch field is set.
     */
    @java.lang.Override
    public boolean hasIfGenerationNotMatch() {
        return (0 != (bitField0_ & 0x00000002));
    }

    /**
     * <pre>
     * Makes the operation conditional on whether the object's current
     * generation does not match the given value. If no live object exists, the
     * precondition fails. Setting to 0 makes the operation succeed only if
     * there is a live version of the object.
     * </pre>
     *
     * <code>optional int64 if_generation_not_match = 4;</code>
     *
     * @return The ifGenerationNotMatch.
     */
    @java.lang.Override
    public long getIfGenerationNotMatch() {
        return ifGenerationNotMatch_;
    }

    public static final int IF_METAGENERATION_MATCH_FIELD_NUMBER = 5;

    private long ifMetagenerationMatch_;

    /**
     * <pre>
     * Makes the operation conditional on whether the object's current
     * metageneration matches the given value.
     * </pre>
     *
     * <code>optional int64 if_metageneration_match = 5;</code>
     *
     * @return Whether the ifMetagenerationMatch field is set.
     */
    @java.lang.Override
    public boolean hasIfMetagenerationMatch() {
        return (0 != (bitField0_ & 0x00000004));
    }

    /**
     * <pre>
     * Makes the operation conditional on whether the object's current
     * metageneration matches the given value.
     * </pre>
     *
     * <code>optional int64 if_metageneration_match = 5;</code>
     *
     * @return The ifMetagenerationMatch.
     */
    @java.lang.Override
    public long getIfMetagenerationMatch() {
        return ifMetagenerationMatch_;
    }

    public static final int IF_METAGENERATION_NOT_MATCH_FIELD_NUMBER = 6;

    private long ifMetagenerationNotMatch_;

    /**
     * <pre>
     * Makes the operation conditional on whether the object's current
     * metageneration does not match the given value.
     * </pre>
     *
     * <code>optional int64 if_metageneration_not_match = 6;</code>
     *
     * @return Whether the ifMetagenerationNotMatch field is set.
     */
    @java.lang.Override
    public boolean hasIfMetagenerationNotMatch() {
        return (0 != (bitField0_ & 0x00000008));
    }

    /**
     * <pre>
     * Makes the operation conditional on whether the object's current
     * metageneration does not match the given value.
     * </pre>
     *
     * <code>optional int64 if_metageneration_not_match = 6;</code>
     *
     * @return The ifMetagenerationNotMatch.
     */
    @java.lang.Override
    public long getIfMetagenerationNotMatch() {
        return ifMetagenerationNotMatch_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (1 == isInitialized)
            return true;
        if (0 == isInitialized)
            return false;
        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (null != resource_) {
            output.writeMessage(1, getResource());
        }
        if ((0 != (bitField0_ & 0x00000001))) {
            output.writeInt64(3, ifGenerationMatch_);
        }
        if ((0 != (bitField0_ & 0x00000002))) {
            output.writeInt64(4, ifGenerationNotMatch_);
        }
        if ((0 != (bitField0_ & 0x00000004))) {
            output.writeInt64(5, ifMetagenerationMatch_);
        }
        if ((0 != (bitField0_ & 0x00000008))) {
            output.writeInt64(6, ifMetagenerationNotMatch_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(predefinedAcl_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 7, predefinedAcl_);
        }
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (-1 != size)
            return size;
        size = 0;
        if (null != resource_) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getResource());
        }
        if ((0 != (bitField0_ & 0x00000001))) {
            size += com.google.protobuf.CodedOutputStream.computeInt64Size(3, ifGenerationMatch_);
        }
        if ((0 != (bitField0_ & 0x00000002))) {
            size += com.google.protobuf.CodedOutputStream.computeInt64Size(4, ifGenerationNotMatch_);
        }
        if ((0 != (bitField0_ & 0x00000004))) {
            size += com.google.protobuf.CodedOutputStream.computeInt64Size(5, ifMetagenerationMatch_);
        }
        if ((0 != (bitField0_ & 0x00000008))) {
            size += com.google.protobuf.CodedOutputStream.computeInt64Size(6, ifMetagenerationNotMatch_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(predefinedAcl_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, predefinedAcl_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof com.google.storage.v2.WriteObjectSpec)) {
            return super.equals(obj);
        }
        com.google.storage.v2.WriteObjectSpec other = (com.google.storage.v2.WriteObjectSpec) obj;
        if (other.hasResource() != hasResource())
            return false;
        if (hasResource()) {
            if (!getResource().equals(other.getResource()))
                return false;
        }
        if (!getPredefinedAcl().equals(other.getPredefinedAcl()))
            return false;
        if (other.hasIfGenerationMatch() != hasIfGenerationMatch())
            return false;
        if (hasIfGenerationMatch()) {
            if (other.getIfGenerationMatch() != getIfGenerationMatch())
                return false;
        }
        if (other.hasIfGenerationNotMatch() != hasIfGenerationNotMatch())
            return false;
        if (hasIfGenerationNotMatch()) {
            if (other.getIfGenerationNotMatch() != getIfGenerationNotMatch())
                return false;
        }
        if (other.hasIfMetagenerationMatch() != hasIfMetagenerationMatch())
            return false;
        if (hasIfMetagenerationMatch()) {
            if (other.getIfMetagenerationMatch() != getIfMetagenerationMatch())
                return false;
        }
        if (other.hasIfMetagenerationNotMatch() != hasIfMetagenerationNotMatch())
            return false;
        if (hasIfMetagenerationNotMatch()) {
            if (other.getIfMetagenerationNotMatch() != getIfMetagenerationNotMatch())
                return false;
        }
        if (!unknownFields.equals(other.unknownFields))
            return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (0 != memoizedHashCode) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasResource()) {
            hash = (37 * hash) + RESOURCE_FIELD_NUMBER;
            hash = (53 * hash) + getResource().hashCode();
        }
        hash = (37 * hash) + PREDEFINED_ACL_FIELD_NUMBER;
        hash = (53 * hash) + getPredefinedAcl().hashCode();
        if (hasIfGenerationMatch()) {
            hash = (37 * hash) + IF_GENERATION_MATCH_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getIfGenerationMatch());
        }
        if (hasIfGenerationNotMatch()) {
            hash = (37 * hash) + IF_GENERATION_NOT_MATCH_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getIfGenerationNotMatch());
        }
        if (hasIfMetagenerationMatch()) {
            hash = (37 * hash) + IF_METAGENERATION_MATCH_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getIfMetagenerationMatch());
        }
        if (hasIfMetagenerationNotMatch()) {
            hash = (37 * hash) + IF_METAGENERATION_NOT_MATCH_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getIfMetagenerationNotMatch());
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.google.storage.v2.WriteObjectSpec parseFrom(java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.google.storage.v2.WriteObjectSpec parseFrom(java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.google.storage.v2.WriteObjectSpec parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.google.storage.v2.WriteObjectSpec parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.google.storage.v2.WriteObjectSpec parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.google.storage.v2.WriteObjectSpec parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.google.storage.v2.WriteObjectSpec parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.google.storage.v2.WriteObjectSpec parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.google.storage.v2.WriteObjectSpec parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.google.storage.v2.WriteObjectSpec parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.google.storage.v2.WriteObjectSpec parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.google.storage.v2.WriteObjectSpec parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.google.storage.v2.WriteObjectSpec prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return DEFAULT_INSTANCE == this ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * <pre>
     * Describes an attempt to insert an object, possibly over multiple requests.
     * </pre>
     *
     * Protobuf type {@code google.storage.v2.WriteObjectSpec}
     */
    public static final class // @@protoc_insertion_point(builder_implements:google.storage.v2.WriteObjectSpec)
    // @@protoc_insertion_point(builder_implements:google.storage.v2.WriteObjectSpec)
    Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements com.google.storage.v2.WriteObjectSpecOrBuilder {

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.google.storage.v2.StorageProto.internal_static_google_storage_v2_WriteObjectSpec_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.google.storage.v2.StorageProto.internal_static_google_storage_v2_WriteObjectSpec_fieldAccessorTable.ensureFieldAccessorsInitialized(com.google.storage.v2.WriteObjectSpec.class, com.google.storage.v2.WriteObjectSpec.Builder.class);
        }

        // Construct using com.google.storage.v2.WriteObjectSpec.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            if (null != resourceBuilder_) {
                resource_ = null;
                resourceBuilder_ = null;
            } else {
                resource_ = null;
            }
            predefinedAcl_ = "";
            ifGenerationMatch_ = 0L;
            bitField0_ = (bitField0_ & ~0x00000001);
            ifGenerationNotMatch_ = 0L;
            bitField0_ = (bitField0_ & ~0x00000002);
            ifMetagenerationMatch_ = 0L;
            bitField0_ = (bitField0_ & ~0x00000004);
            ifMetagenerationNotMatch_ = 0L;
            bitField0_ = (bitField0_ & ~0x00000008);
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return com.google.storage.v2.StorageProto.internal_static_google_storage_v2_WriteObjectSpec_descriptor;
        }

        @java.lang.Override
        public com.google.storage.v2.WriteObjectSpec getDefaultInstanceForType() {
            return com.google.storage.v2.WriteObjectSpec.getDefaultInstance();
        }

        @java.lang.Override
        public com.google.storage.v2.WriteObjectSpec build() {
            com.google.storage.v2.WriteObjectSpec result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.google.storage.v2.WriteObjectSpec buildPartial() {
            com.google.storage.v2.WriteObjectSpec result = new com.google.storage.v2.WriteObjectSpec(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (null != resourceBuilder_) {
                result.resource_ = resourceBuilder_.build();
            } else {
                result.resource_ = resource_;
            }
            result.predefinedAcl_ = predefinedAcl_;
            if ((0 != (from_bitField0_ & 0x00000001))) {
                result.ifGenerationMatch_ = ifGenerationMatch_;
                to_bitField0_ |= 0x00000001;
            }
            if ((0 != (from_bitField0_ & 0x00000002))) {
                result.ifGenerationNotMatch_ = ifGenerationNotMatch_;
                to_bitField0_ |= 0x00000002;
            }
            if ((0 != (from_bitField0_ & 0x00000004))) {
                result.ifMetagenerationMatch_ = ifMetagenerationMatch_;
                to_bitField0_ |= 0x00000004;
            }
            if ((0 != (from_bitField0_ & 0x00000008))) {
                result.ifMetagenerationNotMatch_ = ifMetagenerationNotMatch_;
                to_bitField0_ |= 0x00000008;
            }
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (!(other instanceof com.google.storage.v2.WriteObjectSpec)) {
                super.mergeFrom(other);
                return this;
            } else {
                return mergeFrom((com.google.storage.v2.WriteObjectSpec) other);
            }
        }

        public Builder mergeFrom(com.google.storage.v2.WriteObjectSpec other) {
            if (com.google.storage.v2.WriteObjectSpec.getDefaultInstance() == other)
                return this;
            if (other.hasResource()) {
                mergeResource(other.getResource());
            }
            if (!other.getPredefinedAcl().isEmpty()) {
                predefinedAcl_ = other.predefinedAcl_;
                onChanged();
            }
            if (other.hasIfGenerationMatch()) {
                setIfGenerationMatch(other.getIfGenerationMatch());
            }
            if (other.hasIfGenerationNotMatch()) {
                setIfGenerationNotMatch(other.getIfGenerationNotMatch());
            }
            if (other.hasIfMetagenerationMatch()) {
                setIfMetagenerationMatch(other.getIfMetagenerationMatch());
            }
            if (other.hasIfMetagenerationNotMatch()) {
                setIfMetagenerationNotMatch(other.getIfMetagenerationNotMatch());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            com.google.storage.v2.WriteObjectSpec parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.google.storage.v2.WriteObjectSpec) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (null != parsedMessage) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int bitField0_;

        private com.google.storage.v2.Object resource_;

        private com.google.protobuf.SingleFieldBuilderV3<com.google.storage.v2.Object, com.google.storage.v2.Object.Builder, com.google.storage.v2.ObjectOrBuilder> resourceBuilder_;

        /**
         * <pre>
         * Destination object, including its name and its metadata.
         * </pre>
         *
         * <code>.google.storage.v2.Object resource = 1;</code>
         *
         * @return Whether the resource field is set.
         */
        public boolean hasResource() {
            return null != resourceBuilder_ || null != resource_;
        }

        /**
         * <pre>
         * Destination object, including its name and its metadata.
         * </pre>
         *
         * <code>.google.storage.v2.Object resource = 1;</code>
         *
         * @return The resource.
         */
        public com.google.storage.v2.Object getResource() {
            if (null != resourceBuilder_) {
                return resourceBuilder_.getMessage();
            } else {
                return null == resource_ ? com.google.storage.v2.Object.getDefaultInstance() : resource_;
            }
        }

        /**
         * <pre>
         * Destination object, including its name and its metadata.
         * </pre>
         *
         * <code>.google.storage.v2.Object resource = 1;</code>
         */
        public Builder setResource(com.google.storage.v2.Object value) {
            if (null != resourceBuilder_) {
                resourceBuilder_.setMessage(value);
            } else {
                if (null == value) {
                    throw new NullPointerException();
                }
                resource_ = value;
                onChanged();
            }
            return this;
        }

        /**
         * <pre>
         * Destination object, including its name and its metadata.
         * </pre>
         *
         * <code>.google.storage.v2.Object resource = 1;</code>
         */
        public Builder setResource(com.google.storage.v2.Object.Builder builderForValue) {
            if (null != resourceBuilder_) {
                resourceBuilder_.setMessage(builderForValue.build());
            } else {
                resource_ = builderForValue.build();
                onChanged();
            }
            return this;
        }

        /**
         * <pre>
         * Destination object, including its name and its metadata.
         * </pre>
         *
         * <code>.google.storage.v2.Object resource = 1;</code>
         */
        public Builder mergeResource(com.google.storage.v2.Object value) {
            if (null != resourceBuilder_) {
                resourceBuilder_.mergeFrom(value);
            } else {
                if (null == resource_) {
                    resource_ = value;
                } else {
                    resource_ = com.google.storage.v2.Object.newBuilder(resource_).mergeFrom(value).buildPartial();
                }
                onChanged();
            }
            return this;
        }

        /**
         * <pre>
         * Destination object, including its name and its metadata.
         * </pre>
         *
         * <code>.google.storage.v2.Object resource = 1;</code>
         */
        public Builder clearResource() {
            if (null != resourceBuilder_) {
                resource_ = null;
                resourceBuilder_ = null;
            } else {
                resource_ = null;
                onChanged();
            }
            return this;
        }

        /**
         * <pre>
         * Destination object, including its name and its metadata.
         * </pre>
         *
         * <code>.google.storage.v2.Object resource = 1;</code>
         */
        public com.google.storage.v2.Object.Builder getResourceBuilder() {
            onChanged();
            return getResourceFieldBuilder().getBuilder();
        }

        /**
         * <pre>
         * Destination object, including its name and its metadata.
         * </pre>
         *
         * <code>.google.storage.v2.Object resource = 1;</code>
         */
        public com.google.storage.v2.ObjectOrBuilder getResourceOrBuilder() {
            if (null == resourceBuilder_) {
                return null == resource_ ? com.google.storage.v2.Object.getDefaultInstance() : resource_;
            } else {
                return resourceBuilder_.getMessageOrBuilder();
            }
        }

        /**
         * <pre>
         * Destination object, including its name and its metadata.
         * </pre>
         *
         * <code>.google.storage.v2.Object resource = 1;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<com.google.storage.v2.Object, com.google.storage.v2.Object.Builder, com.google.storage.v2.ObjectOrBuilder> getResourceFieldBuilder() {
            if (null == resourceBuilder_) {
                resourceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<com.google.storage.v2.Object, com.google.storage.v2.Object.Builder, com.google.storage.v2.ObjectOrBuilder>(getResource(), getParentForChildren(), isClean());
                resource_ = null;
            }
            return resourceBuilder_;
        }

        private java.lang.Object predefinedAcl_ = "";

        /**
         * <pre>
         * Apply a predefined set of access controls to this object.
         * Valid values are "authenticatedRead", "bucketOwnerFullControl",
         * "bucketOwnerRead", "private", "projectPrivate", or "publicRead".
         * </pre>
         *
         * <code>string predefined_acl = 7;</code>
         *
         * @return The predefinedAcl.
         */
        public java.lang.String getPredefinedAcl() {
            java.lang.Object ref = predefinedAcl_;
            if ((ref instanceof java.lang.String)) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                predefinedAcl_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * Apply a predefined set of access controls to this object.
         * Valid values are "authenticatedRead", "bucketOwnerFullControl",
         * "bucketOwnerRead", "private", "projectPrivate", or "publicRead".
         * </pre>
         *
         * <code>string predefined_acl = 7;</code>
         *
         * @return The bytes for predefinedAcl.
         */
        public com.google.protobuf.ByteString getPredefinedAclBytes() {
            java.lang.Object ref = predefinedAcl_;
            if (!(ref instanceof String)) {
                return (com.google.protobuf.ByteString) ref;
            } else {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                predefinedAcl_ = b;
                return b;
            }
        }

        /**
         * <pre>
         * Apply a predefined set of access controls to this object.
         * Valid values are "authenticatedRead", "bucketOwnerFullControl",
         * "bucketOwnerRead", "private", "projectPrivate", or "publicRead".
         * </pre>
         *
         * <code>string predefined_acl = 7;</code>
         *
         * @param value The predefinedAcl to set.
         * @return This builder for chaining.
         */
        public Builder setPredefinedAcl(java.lang.String value) {
            if (null == value) {
                throw new NullPointerException();
            }
            predefinedAcl_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Apply a predefined set of access controls to this object.
         * Valid values are "authenticatedRead", "bucketOwnerFullControl",
         * "bucketOwnerRead", "private", "projectPrivate", or "publicRead".
         * </pre>
         *
         * <code>string predefined_acl = 7;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearPredefinedAcl() {
            predefinedAcl_ = getDefaultInstance().getPredefinedAcl();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Apply a predefined set of access controls to this object.
         * Valid values are "authenticatedRead", "bucketOwnerFullControl",
         * "bucketOwnerRead", "private", "projectPrivate", or "publicRead".
         * </pre>
         *
         * <code>string predefined_acl = 7;</code>
         *
         * @param value The bytes for predefinedAcl to set.
         * @return This builder for chaining.
         */
        public Builder setPredefinedAclBytes(com.google.protobuf.ByteString value) {
            if (null == value) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            predefinedAcl_ = value;
            onChanged();
            return this;
        }

        private long ifGenerationMatch_;

        /**
         * <pre>
         * Makes the operation conditional on whether the object's current
         * generation matches the given value. Setting to 0 makes the operation
         * succeed only if there are no live versions of the object.
         * </pre>
         *
         * <code>optional int64 if_generation_match = 3;</code>
         *
         * @return Whether the ifGenerationMatch field is set.
         */
        @java.lang.Override
        public boolean hasIfGenerationMatch() {
            return (0 != (bitField0_ & 0x00000001));
        }

        /**
         * <pre>
         * Makes the operation conditional on whether the object's current
         * generation matches the given value. Setting to 0 makes the operation
         * succeed only if there are no live versions of the object.
         * </pre>
         *
         * <code>optional int64 if_generation_match = 3;</code>
         *
         * @return The ifGenerationMatch.
         */
        @java.lang.Override
        public long getIfGenerationMatch() {
            return ifGenerationMatch_;
        }

        /**
         * <pre>
         * Makes the operation conditional on whether the object's current
         * generation matches the given value. Setting to 0 makes the operation
         * succeed only if there are no live versions of the object.
         * </pre>
         *
         * <code>optional int64 if_generation_match = 3;</code>
         *
         * @param value The ifGenerationMatch to set.
         * @return This builder for chaining.
         */
        public Builder setIfGenerationMatch(long value) {
            bitField0_ |= 0x00000001;
            ifGenerationMatch_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Makes the operation conditional on whether the object's current
         * generation matches the given value. Setting to 0 makes the operation
         * succeed only if there are no live versions of the object.
         * </pre>
         *
         * <code>optional int64 if_generation_match = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearIfGenerationMatch() {
            bitField0_ = (bitField0_ & ~0x00000001);
            ifGenerationMatch_ = 0L;
            onChanged();
            return this;
        }

        private long ifGenerationNotMatch_;

        /**
         * <pre>
         * Makes the operation conditional on whether the object's current
         * generation does not match the given value. If no live object exists, the
         * precondition fails. Setting to 0 makes the operation succeed only if
         * there is a live version of the object.
         * </pre>
         *
         * <code>optional int64 if_generation_not_match = 4;</code>
         *
         * @return Whether the ifGenerationNotMatch field is set.
         */
        @java.lang.Override
        public boolean hasIfGenerationNotMatch() {
            return (0 != (bitField0_ & 0x00000002));
        }

        /**
         * <pre>
         * Makes the operation conditional on whether the object's current
         * generation does not match the given value. If no live object exists, the
         * precondition fails. Setting to 0 makes the operation succeed only if
         * there is a live version of the object.
         * </pre>
         *
         * <code>optional int64 if_generation_not_match = 4;</code>
         *
         * @return The ifGenerationNotMatch.
         */
        @java.lang.Override
        public long getIfGenerationNotMatch() {
            return ifGenerationNotMatch_;
        }

        /**
         * <pre>
         * Makes the operation conditional on whether the object's current
         * generation does not match the given value. If no live object exists, the
         * precondition fails. Setting to 0 makes the operation succeed only if
         * there is a live version of the object.
         * </pre>
         *
         * <code>optional int64 if_generation_not_match = 4;</code>
         *
         * @param value The ifGenerationNotMatch to set.
         * @return This builder for chaining.
         */
        public Builder setIfGenerationNotMatch(long value) {
            bitField0_ |= 0x00000002;
            ifGenerationNotMatch_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Makes the operation conditional on whether the object's current
         * generation does not match the given value. If no live object exists, the
         * precondition fails. Setting to 0 makes the operation succeed only if
         * there is a live version of the object.
         * </pre>
         *
         * <code>optional int64 if_generation_not_match = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearIfGenerationNotMatch() {
            bitField0_ = (bitField0_ & ~0x00000002);
            ifGenerationNotMatch_ = 0L;
            onChanged();
            return this;
        }

        private long ifMetagenerationMatch_;

        /**
         * <pre>
         * Makes the operation conditional on whether the object's current
         * metageneration matches the given value.
         * </pre>
         *
         * <code>optional int64 if_metageneration_match = 5;</code>
         *
         * @return Whether the ifMetagenerationMatch field is set.
         */
        @java.lang.Override
        public boolean hasIfMetagenerationMatch() {
            return (0 != (bitField0_ & 0x00000004));
        }

        /**
         * <pre>
         * Makes the operation conditional on whether the object's current
         * metageneration matches the given value.
         * </pre>
         *
         * <code>optional int64 if_metageneration_match = 5;</code>
         *
         * @return The ifMetagenerationMatch.
         */
        @java.lang.Override
        public long getIfMetagenerationMatch() {
            return ifMetagenerationMatch_;
        }

        /**
         * <pre>
         * Makes the operation conditional on whether the object's current
         * metageneration matches the given value.
         * </pre>
         *
         * <code>optional int64 if_metageneration_match = 5;</code>
         *
         * @param value The ifMetagenerationMatch to set.
         * @return This builder for chaining.
         */
        public Builder setIfMetagenerationMatch(long value) {
            bitField0_ |= 0x00000004;
            ifMetagenerationMatch_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Makes the operation conditional on whether the object's current
         * metageneration matches the given value.
         * </pre>
         *
         * <code>optional int64 if_metageneration_match = 5;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearIfMetagenerationMatch() {
            bitField0_ = (bitField0_ & ~0x00000004);
            ifMetagenerationMatch_ = 0L;
            onChanged();
            return this;
        }

        private long ifMetagenerationNotMatch_;

        /**
         * <pre>
         * Makes the operation conditional on whether the object's current
         * metageneration does not match the given value.
         * </pre>
         *
         * <code>optional int64 if_metageneration_not_match = 6;</code>
         *
         * @return Whether the ifMetagenerationNotMatch field is set.
         */
        @java.lang.Override
        public boolean hasIfMetagenerationNotMatch() {
            return (0 != (bitField0_ & 0x00000008));
        }

        /**
         * <pre>
         * Makes the operation conditional on whether the object's current
         * metageneration does not match the given value.
         * </pre>
         *
         * <code>optional int64 if_metageneration_not_match = 6;</code>
         *
         * @return The ifMetagenerationNotMatch.
         */
        @java.lang.Override
        public long getIfMetagenerationNotMatch() {
            return ifMetagenerationNotMatch_;
        }

        /**
         * <pre>
         * Makes the operation conditional on whether the object's current
         * metageneration does not match the given value.
         * </pre>
         *
         * <code>optional int64 if_metageneration_not_match = 6;</code>
         *
         * @param value The ifMetagenerationNotMatch to set.
         * @return This builder for chaining.
         */
        public Builder setIfMetagenerationNotMatch(long value) {
            bitField0_ |= 0x00000008;
            ifMetagenerationNotMatch_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Makes the operation conditional on whether the object's current
         * metageneration does not match the given value.
         * </pre>
         *
         * <code>optional int64 if_metageneration_not_match = 6;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearIfMetagenerationNotMatch() {
            bitField0_ = (bitField0_ & ~0x00000008);
            ifMetagenerationNotMatch_ = 0L;
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }
        // @@protoc_insertion_point(builder_scope:google.storage.v2.WriteObjectSpec)
    }

    // @@protoc_insertion_point(class_scope:google.storage.v2.WriteObjectSpec)
    private static final com.google.storage.v2.WriteObjectSpec DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new com.google.storage.v2.WriteObjectSpec();
    }

    public static com.google.storage.v2.WriteObjectSpec getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WriteObjectSpec> PARSER = new com.google.protobuf.AbstractParser<WriteObjectSpec>() {

        @java.lang.Override
        public WriteObjectSpec parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
            return new WriteObjectSpec(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<WriteObjectSpec> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WriteObjectSpec> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.storage.v2.WriteObjectSpec getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
}
